title: Alexandre Bulatović
author: Alexandre Bulatović
#email: your-email@domain.com
description:
  Alexandre Bulatović portfolio and résumé.
#set to true to show excerpts on the homepage
show_excerpts: true 
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
collections:
  post:
    output: true
    #sort_by: rank
    permalink: /:slug
    
plainwhite:
  name: Alexandre Bulatović
  tagline: Software Developer
  date_format: "%b %-d, %Y"
  sitemap: true
  navigation:
    - title: Personal and school projects
      url: "."
    - title: About me
      url: "../about.html"

  # generate social links in footer
  social_links:
    github:  alexandrebulatovic
    linkedIn: in/alexandre-bulatović-119a841a3/
    #rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed